version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apigetconso
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
